#include "nuttx/config.h"

#ifdef CONFIG_BSP_USING_UART1
#define BSP_USING_UART1
#ifdef CONFIG_BSP_UART1_RX_USING_DMA
#define BSP_UART1_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART1_TX_USING_DMA
#define BSP_UART1_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART2
#define BSP_USING_UART2
#ifdef CONFIG_BSP_UART2_RX_USING_DMA
#define BSP_UART2_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART2_TX_USING_DMA
#define BSP_UART2_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART3
#define BSP_USING_UART3
#ifdef CONFIG_BSP_UART3_RX_USING_DMA
#define BSP_UART3_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART3_TX_USING_DMA
#define BSP_UART3_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART4
#define BSP_USING_UART4
#ifdef CONFIG_BSP_UART4_RX_USING_DMA
#define BSP_UART4_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART4_TX_USING_DMA
#define BSP_UART4_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART5
#define BSP_USING_UART5
#ifdef CONFIG_BSP_UART5_RX_USING_DMA
#define BSP_UART5_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART5_TX_USING_DMA
#define BSP_UART5_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_UART6
#define BSP_USING_UART6
#ifdef CONFIG_BSP_UART6_RX_USING_DMA
#define BSP_UART6_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_UART6_TX_USING_DMA
#define BSP_UART6_TX_USING_DMA
#endif
#endif

#ifdef CONFIG_BSP_USING_LPUART1
#define BSP_USING_LPUART1
#ifdef CONFIG_BSP_LPUART1_RX_USING_DMA
#define BSP_LPUART1_RX_USING_DMA
#endif
#ifdef CONFIG_BSP_LPUART1_TX_USING_DMA
#define BSP_LPUART1_TX_USING_DMA
#endif
#endif
